// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/trpc': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/server/trpc/server').default>>>>
    }
    '/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../build/auth/auth/auth').default>>>>
    }
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../#vinxi/spa/client').default>>>>
    }
  }
}
export {}